# This file was generated by symflow CLI v8.0.2 on 2023-08-07 at 19:15 UTC.
# PLEASE DO NOT RENAME THIS FILE. If this file's name is not `environment.tf`, you will not be able to run `symflow generate` to create new Flows.


locals {
  # This variable is necessary for `symflow generate` to work. Do not remove it.
  environment_name = "prod"
}

provider "sym" {
  org = "sym-demo"
}

# The sym_environment is a container for sym_flows that share configuration values
# (e.g. shared integrations or error logging)
resource "sym_environment" "this" {
  name            = local.environment_name
  error_logger_id = sym_error_logger.slack.id
  runtime_id      = module.runtime_connector.sym_runtime.id

  integrations = {
    slack_id = sym_integration.slack.id
  }
}

resource "sym_integration" "slack" {
  type = "slack"
  name = "${local.environment_name}-slack"

  # The external_id for slack integrations is the Slack Workspace ID
  external_id = "T05LS5M1DC4"
}

# This sym_error_logger will output any warnings and errors that occur during
# execution of a sym_flow to a specified channel in Slack.
resource "sym_error_logger" "slack" {
  integration_id = sym_integration.slack.id
  destination    = "#sym-errors"
}
